version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-shopdevgo
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "shopdevgo"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis-shopdevgo
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
